---
version: "3.9"
services:
  service-recon:
    image: registry.gitlab.com/patrickdung/pod-recon:0.1
    #image: registry.gitlab.com/patrickdung/docker-images/pod-recon:0.1
    pull_policy: always
    container_name: "pod-recon"
    hostname: "pod-recon"
    cap_drop:
      - all
    cap_add:
      - net_raw
    #  - net_admin
    #  - setuid
    #  - setgid
    #entrypoint: /usr/bin/sleep
    #command: [3600]
    # user: root
